import React, { useRef } from 'react';
import { QRCodeSVG, QRCodeCanvas } from 'qrcode.react';
import { Download, Printer, QrCode } from 'lucide-react';

export default function QRCodeCard({
  value,
  onNotify
}) {
  const qrCanvasRef = useRef(null);

  const handleDownload = () => {
    if (!value.trim()) {
      onNotify?.({ type: 'error', message: 'No text available to generate QR download' });
      return;
    }

    try {
      const canvas = qrCanvasRef.current?.querySelector('canvas');
      if (!canvas) {
        onNotify?.({ type: 'error', message: 'Could not find QR canvas' });
        return;
      }

      const imageUri = canvas.toDataURL('image/png');
      const link = document.createElement('a');
      const filename = `QR_${value.replace(/[^a-zA-Z0-9_-]/g, '_')}.png`;
      link.href = imageUri;
      link.download = filename;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);

      onNotify?.({ type: 'success', message: `Downloaded ${filename}` });
    } catch (err) {
      onNotify?.({ type: 'error', message: 'Download failed' });
    }
  };


  const handlePrint = () => {
    if (!value.trim()) return;
    const printWindow = window.open('', '_blank');
    if (!printWindow) return;

    const canvas = qrCanvasRef.current?.querySelector('canvas');
    const dataUrl = canvas ? canvas.toDataURL('image/png') : '';

    printWindow.document.write(`
      <!DOCTYPE html>
      <html>
        <head>
          <title>Print QR - ${value}</title>
          <style>
            body {
              font-family: system-ui, sans-serif;
              display: flex;
              flex-direction: column;
              align-items: center;
              justify-content: center;
              height: 100vh;
              margin: 0;
            }
            .label-box {
              border: 2px dashed #333;
              padding: 24px;
              border-radius: 12px;
              text-align: center;
              max-width: 320px;
            }
            img {
              width: 220px;
              height: 220px;
            }
            h2 {
              margin: 12px 0 4px;
              font-size: 20px;
              letter-spacing: 1px;
            }
            p {
              margin: 0;
              color: #666;
              font-size: 12px;
            }
          </style>
        </head>
        <body>
          <div class="label-box">
            <img src="${dataUrl}" alt="${value}" />
            <h2>${value}</h2>
            <p>Generated by Online QR Generator</p>
          </div>
          <script>
            window.onload = function() {
              window.print();
              window.close();
            }
          </script>
        </body>
      </html>
    `);
    printWindow.document.close();
  };

  const hasValue = Boolean(value.trim());

  return (
    <div className="bg-[#1b1d24] border border-zinc-800/80 rounded-2xl p-5 sm:p-6 shadow-xl flex flex-col items-center justify-center text-center">
      <div className="w-full flex items-center justify-between pb-3 mb-4 border-b border-zinc-800">
        <div className="flex items-center gap-2 text-zinc-300 font-semibold text-base">
          <QrCode className="w-4 h-4 text-[#00e676]" />
          <span>QR Code Display</span>
        </div>
      </div>

      <div className="relative group my-2">
        <div className="bg-white p-4 sm:p-5 rounded-2xl shadow-2xl transition-all duration-300 transform group-hover:scale-[1.02]">
          {hasValue ? (
            <div ref={qrCanvasRef} className="flex items-center justify-center">
              <QRCodeCanvas
                value={value}
                size={200}
                level="H"
                includeMargin={true}
              />
            </div>
          ) : (
            <div className="w-48 h-48 flex flex-col items-center justify-center text-zinc-400 border-2 border-dashed border-zinc-300 rounded-xl">
              <QrCode className="w-12 h-12 text-zinc-300 mb-2" />
              <span className="text-xs font-medium">Enter or generate code</span>
            </div>
          )}
        </div>
      </div>

      <div className="mt-4 mb-5 w-full">
        <div className="text-xs text-zinc-400 mb-1">Encoded Content:</div>
        <div className="bg-zinc-900 border border-zinc-750 px-3 py-2 rounded-xl font-mono text-sm sm:text-base font-bold text-[#00e676] tracking-wider break-all max-w-full">
          {hasValue ? value : 'WAITING FOR INPUT...'}
        </div>
      </div>

      <div className="flex flex-wrap items-center justify-center gap-2 w-full">
        <button
          type="button"
          onClick={handleDownload}
          disabled={!hasValue}
          className="flex-1 min-w-[120px] flex items-center justify-center gap-1.5 py-2 px-3 rounded-xl bg-zinc-800 hover:bg-zinc-700 text-zinc-200 hover:text-white text-xs font-semibold border border-zinc-700 transition-colors disabled:opacity-40 disabled:cursor-not-allowed cursor-pointer"
        >
          <Download className="w-3.5 h-3.5 text-[#00e676]" />
          <span>Save PNG</span>
        </button>

        <button
          type="button"
          onClick={handlePrint}
          disabled={!hasValue}
          className="flex-1 min-w-[100px] flex items-center justify-center gap-1.5 py-2 px-3 rounded-xl bg-zinc-800 hover:bg-zinc-700 text-zinc-200 hover:text-white text-xs font-semibold border border-zinc-700 transition-colors disabled:opacity-40 disabled:cursor-not-allowed cursor-pointer"
        >
          <Printer className="w-3.5 h-3.5 text-amber-400" />
          <span>Print</span>
        </button>
      </div>
    </div>
  );
}
